### ISSUE TITLE
Updated charts can end up in "wrong" folder

### ISSUE THREAD

**Issue by transmitterdan** [nohal/chartdldr_pi#36]
This isn't a bug in the downloader. Rather it is something that will probably confuse newbies and we should prepare for it.

If you have existing charts in hierarchical folders and you tell the chart downloader the wrong thing unexpected results might happen. For example, suppose you have all your ENC charts and RNC charts for a region under some folders like this:

~/charts/texas/ENC_ROOT
~/charts/texas/BSB_ROOT

But you tell the chart downloader that your charts are in

~/charts/texas

The downloader will happily check the dates of your charts and tell you that some are up to date and some need updating. It doesn't complain that there are in fact no charts in ~/charts/texas.

If you select to update the revised charts it will put the new charts in ~/charts/texas and leave the old charts where they were. A newbie might become confused by that. What will OpenCPN do in such a case? Will it only show the chart from the higher level or will it also show the out of date chart further down the directory tree?

**Comment by nohal** [comment]
If I remember well, just the newer chart. But we should try to do something about this - not move anything anywhere, but probably issue some sort of a warning.
The things to check might be:
- there already is a chart source pointed to the same location
- the actual charts are more than 1 (2 if we count BSB_ROOT/ENC_ROOT) directory level bellow

The problem is, as you have already seen on the forum, there probably is no way to make the information clear enough (but packaging OpenCPN with all the legal chart material and install it all pre-set). Maybe a gnome should materialize next to the keyboard and say "Excuse me, Sir, I will set the stuff up for you" :)

Luckily a completely new user probably won't have this problem in most cases - Will have no pre-installed charts and should just accept the defaults...

**Comment by rgleason** [comment]
If user could see the path they selected it would help a lot!!
At present the Browse path is selected and then masked by the length of the path in the path area.
The width needs to be increased.
I have incorrectly selected the path (folder above or below) several times and only realized it after starting download.  Had to hit stop, correct path using Edit and start again.  Then I had to go in and delete mistaken files that had been downloaded.

Of course this is avoided if users use the predetermined path setup. I have found it better to put US Regions in separate folders, for speed and selectivity. I can create Chart Groups and select a Region etc.

**Comment by rgleason** [comment]
My comment just above about width of Catalog  Add and Edit windows is fixed (wider now..)
Also the default path for Windows, eg:  C:\ProgramData\opencpn\Charts\RNC\US_REGION02 now  makes a good deal of sense (I am going to adjust my chart directories accordingly).  I think users will find this default setup good because it puts charts in the same directory as other OpenCPN data.
chartdldr_pi-0.5-ov4.0-h-22a1943-win32   ---> commit 22a1943

**Comment by rgleason** [comment]
In certain cases...
The downloader will happily check the dates of your charts and tell you that some are up to date and some need updating. It doesn't complain that there are in fact no charts in ~/charts/texas.

If you select to update the revised charts it will put the new charts in ~/charts/texas and leave the old charts where they were. A newbie might become confused by that. What will OpenCPN do in such a case? Will it only show the chart from the higher level or will it also show the out of date chart further down the directory tree?

I'm not so sure there is much the chart downloader can do if New Users do not understand pathnames but perhaps there is some way of  "Initiating a 'search' for charts, listing the directories and checking the correspondence of directories and wether or not the charts are updated. That's a pretty tall order.    

--Also I have lots of charts I keep in a completely separate directory for future use, so that they do not slow down and interfere with my main charts directory. Such a search for charts might become quite excessive in my case.  ...I'd rather know what I am doing.

**Comment by transmitterdan** [comment]
As long as the "separate" directory is not below where the chart catalog is kept then the downloader will ignore them. Also, you can keep your "separate" directory up to date with the downloader but OpenCPN will ignore it if you don't list it (or a parent directory) in the Charts tab.

**Comment by rgleason** [comment]
Good points. Is it worth explaining this in the existing users documentation?

**Comment by transmitterdan** [comment]
I think the directory structure of charts in general should be explained in the O docs. If the O docs explained it well we wouldn’t have much to say in the downloader docs.

**Comment by rgleason** [comment]
Below the "Path to the charts" defined in "Preferences" is it possible or desired that the chartdldr
try to "find" missing  or uncataloged chart folders by scan all directories below the main preferences chart path that do not have a Catalog.xml and compare each directory with known directories in the catalogs? 
Then what?  Just show those 'lost' directories, or try to match them up with the appropriate catalog?

This sounds like a lot of work to me..

**Comment by rgleason** [comment]
Here is what we have regarding Directory Structure for Charts, look under "Where do I keep my Charts?"   It is all good advice, to keep it in a safe directory and treat it like data,...but not very specific.
http://opencpn.org/ocpn/installing_charts

How should we augment this?

**Comment by rgleason** [comment]
Pavel wrote:

> If I remember well, just the newer chart. But we should try to do something about this - not move >anything anywhere, but probably issue some sort of a warning.
> The things to check might be:
> 
>    there already is a chart source pointed to the same location
>    the actual charts are more than 1 (2 if we count BSB_ROOT/ENC_ROOT) directory level bellow
> 
> The problem is, as you have already seen on the forum, there probably is no way to make the >information clear enough

**Comment by nohal** [comment]
If there still is an issue with the current plugin version integrated in OpenCPN, please open it for OpenCPN, this repository is going to be switched to archive mode.
